name: DisTest
main: com.kiss_the_rain8677.MCflu.MainPlugin
version: 1.0
author: kissTheRain
depend:
  - Vault
commands:
  showdis:
    description: "show the nearest player's dis to you"
    usage: "usage:/showDis"


  setMaxHealth:
    description: "set player's max health"
    usage: "usage:/setMaxHealth [player's name+maxVal]"


  showMaxHealth:
    description: "show player's max health"
    usage: "usage:/showMaxHealth [player's name]"

  invent:
    description: "show inventory"
    usage: "invent"



